// import the makeStyles function from the @material-ui/styles library
import { makeStyles } from '@mui/styles';

// export the function generated by the makeStyles function
export default makeStyles((theme) => ({
  // the styles for the container element
  container: {
    // the display property
    display: 'flex',
    // the justify-content property
    justifyContent: 'center',
    // the align-items property
    alignItems: 'center',
  },
  // the styles for the pagination element
  pagination: {
    // the color property using the primary color from the theme
    color: theme.palette.primary.main,
  },
}));
